export type LegalPolicyId = "terms" | "privacy" | "cookies";

export type LegalPolicy = {
  id: LegalPolicyId;
  title: string;
  updated: string;
  /** Optional subtitle shown under the title (e.g. entity / draft status). */
  subtitle?: string;
  sections: { heading: string; body: string }[];
};

export const LEGAL_POLICIES: Record<LegalPolicyId, LegalPolicy> = {
  terms: {
    id: "terms",
    title: "Terms of Service",
    updated: "7 September 2026",
    subtitle:
      "INVESTIO GROUP OF COMPANIES (PTY) LTD · Registration No. 2026/546441/07 · Republic of South Africa",
    sections: [
      {
        heading: "About these Terms",
        body: "These Terms of Service govern access to and use of Crowth, including the Crowth website, mobile application, software, APIs, educational content, and related services (the “Platform”). Crowth is an educational and investment-simulation platform designed to help users learn about investing through market information, company comparisons, simulated portfolios, educational content, and AI-powered explanations. Website: https://crowthza.app.",
      },
      {
        heading: "1. About Crowth",
        body: "Crowth is a financial education and investment simulation platform. It allows users to explore market information and company data; compare companies; view charts and market information; create and manage simulated portfolios; track simulated portfolio performance; receive educational explanations and AI-generated information; and learn about investing in a simple and accessible way. Crowth is designed for learning and simulation, not for managing real investments. Demo portfolios and balances are simulations.",
      },
      {
        heading: "2. Educational use only",
        body: "Crowth is provided for educational and informational purposes only. Crowth does not provide personalised financial advice, investment advice, tax advice, or legal advice; act as a broker or investment manager; execute purchases or sales of securities; hold or manage customer funds; open or manage brokerage accounts; or guarantee investment returns or financial outcomes. Any portfolio balance, profit, loss, performance figure, forecast, score, rating, prediction, or simulation shown on Crowth is intended for educational purposes. You are responsible for your own financial decisions and should obtain advice from a suitably qualified financial professional before making real investment decisions.",
      },
      {
        heading: "3. Market information",
        body: "Crowth may display market prices, company information, charts, market movements, ratings, scores, news-related information, and other financial data obtained from third-party sources. Market information may be delayed, incomplete, incorrect, unavailable, or changed after it is displayed. Crowth does not guarantee that market information is accurate, complete, current, reliable, or available at all times. You should independently verify information before relying on it.",
      },
      {
        heading: "4. AI features",
        body: "Crowth may provide AI-powered features, including AI Advisor responses, company analysis, market insights, scores, ratings, predictions, explanations, and other generated content. AI-generated information may contain mistakes, be incomplete or outdated, misunderstand your question, or produce incorrect financial information. AI output is not personalised financial advice. An AI result such as “Strong Buy”, “Best Long-Term Pick”, a risk level, or an AI score is an educational output and must not be treated as a recommendation to buy, sell, or hold an investment. You should not make financial decisions solely because of information generated by Crowth.",
      },
      {
        heading: "5. Demo portfolios",
        body: "Crowth may allow you to create simulated investment portfolios. Demo portfolios do not contain real money; do not represent actual brokerage accounts; do not create ownership of securities; do not represent actual investment returns; cannot be withdrawn as cash; and cannot be transferred to a real investment account. Portfolio performance shown on Crowth is for educational simulation purposes only.",
      },
      {
        heading: "6. Your account",
        body: "Some Crowth features require an account. When creating an account, you agree to provide accurate information; keep login information secure; keep your password confidential; not share your account with another person; notify us if you believe your account has been accessed without permission; and use the Platform in accordance with these Terms and applicable law. You are responsible for activity carried out through your account unless applicable law provides otherwise.",
      },
      {
        heading: "7. Eligibility",
        body: "You must be at least 18 years old to create an account unless applicable law permits use at a younger age. By using Crowth, you confirm that you have the legal capacity to agree to these Terms, the information you provide is accurate, and you will comply with applicable laws and regulations.",
      },
      {
        heading: "8. Acceptable use",
        body: "You may use Crowth only for lawful purposes. You must not attempt unauthorised access to Crowth; circumvent security controls; introduce malware, viruses, or malicious code; interfere with Platform operations; abuse or overload the Platform; scrape or systematically copy Platform content without permission; use unauthorised bots or automated systems; attempt to access another user’s account; reverse engineer the Platform except where permitted by law; use Crowth for unlawful activities; misrepresent Crowth or your relationship with Crowth; or use the Platform to harm another person or organisation. We may restrict, suspend, or terminate access where we reasonably believe these Terms or applicable laws have been violated.",
      },
      {
        heading: "9. Intellectual property",
        body: "Crowth and its content are protected by applicable intellectual property laws, including its branding, logos, designs, software, interfaces, educational materials, graphics, written content, original data presentations, features, and functionality. Unless expressly permitted, you may not copy, reproduce, modify, distribute, sell, licence, publish, or commercially exploit Crowth’s intellectual property. Nothing in these Terms transfers ownership of Crowth’s intellectual property to you.",
      },
      {
        heading: "10. User content",
        body: "You may provide information, questions, messages, feedback, or other content through Crowth. You remain responsible for content that you submit. You must not submit content that is unlawful, infringes another person’s rights, contains malicious code, attempts to exploit the Platform, or contains information you do not have permission to provide. By submitting feedback or suggestions, you allow us to use that feedback to improve the Platform without an obligation to compensate you.",
      },
      {
        heading: "11. Privacy and personal information",
        body: "Your use of Crowth is also subject to our Privacy Policy and applicable South African privacy laws, including the Protection of Personal Information Act (POPIA) where applicable. We may process information necessary to create and manage accounts, provide Platform services, operate demo portfolios, provide support, improve performance, maintain security, detect fraud and abuse, understand Platform usage, and meet legal obligations. Please refer to the Crowth Privacy Policy for further information.",
      },
      {
        heading: "12. Cookies and analytics",
        body: "Crowth may use cookies and similar technologies for authentication, security, maintaining sessions, remembering preferences, understanding Platform usage, and improving performance. Some cookies may be necessary for the Platform to function properly. You may manage certain cookies through your browser settings, although disabling essential cookies may affect functionality. See also our Cookies Policy.",
      },
      {
        heading: "13. Account deletion",
        body: "You may request deletion of your Crowth account in accordance with our in-app account deletion process. Deleting an account may remove or disable access to account-related information and demo portfolios. Certain information may need to be retained where required by law, necessary for legitimate business purposes, resolving disputes, preventing fraud, or enforcing these Terms.",
      },
      {
        heading: "14. Security",
        body: "We take reasonable steps to protect Crowth and user information, including authentication controls, access controls, encryption in transit, security monitoring, infrastructure protections, and abuse detection. No online service can guarantee complete security. Internet-based services may experience security risks, technical failures, or unauthorised activity despite reasonable safeguards.",
      },
      {
        heading: "15. Third-party services",
        body: "Crowth may depend on third-party services for authentication, hosting, market data, analytics, monitoring, cloud infrastructure, and AI services. Third-party services may have their own terms, policies, availability, and limitations. Crowth is not responsible for failures caused by third-party services to the extent permitted by applicable law.",
      },
      {
        heading: "16. Availability of Crowth",
        body: "We aim to keep Crowth available and working properly, but we do not guarantee uninterrupted access. Crowth may be temporarily unavailable, updated, modified, slowed down, suspended, or discontinued. Maintenance, technical problems, security incidents, third-party failures, or other circumstances may affect availability.",
      },
      {
        heading: "17. No guarantee of financial results",
        body: "Crowth does not guarantee investment profits, better investment decisions, financial success, specific investment performance, or specific market predictions. Past performance or simulated performance should not be considered a guarantee of future results.",
      },
      {
        heading: "18. Limitation of liability",
        body: "To the maximum extent permitted by applicable law, Crowth and INVESTIO GROUP OF COMPANIES (PTY) LTD will not be responsible for losses or damages arising from your use of, or inability to use, the Platform, including losses resulting from reliance on market information, AI-generated content, investment decisions, simulated portfolio performance, third-party services, outages, unauthorised account access, technical failures, or errors or omissions in Platform information. Nothing in these Terms excludes or limits any right or protection that cannot legally be excluded or limited under applicable law.",
      },
      {
        heading: "19. Indemnification",
        body: "To the extent permitted by law, you agree to be responsible for claims, losses, liabilities, costs, or expenses arising from your misuse of Crowth, violation of these Terms, violation of applicable law, infringement of another person’s rights, or unauthorised use of the Platform. This section does not apply to the extent that applicable law does not permit such an obligation.",
      },
      {
        heading: "20. Suspension and termination",
        body: "We may suspend or terminate access if you seriously or repeatedly breach these Terms, your use creates a security risk, fraud or abuse is suspected, you use the Platform unlawfully, or your activity may harm Crowth or other users. You may stop using Crowth at any time. Provisions intended to survive termination, including intellectual property, disclaimers, liability, and governing law, remain applicable.",
      },
      {
        heading: "21. Changes to Crowth",
        body: "We may change, improve, remove, or introduce features from time to time. We will try to provide reasonable notice where a change materially affects users and notice is required by law.",
      },
      {
        heading: "22. Changes to these Terms",
        body: "We may update these Terms from time to time. The Last Updated date will be changed when revisions are made. Where required by applicable law, we will provide appropriate notice of material changes. Your continued use of Crowth after updated Terms become effective means that you accept the updated Terms. If you do not agree, you must stop using Crowth.",
      },
      {
        heading: "23. Governing law",
        body: "These Terms are governed by the laws of the Republic of South Africa. Disputes relating to these Terms or Crowth will be subject to applicable South African courts and dispute-resolution processes, subject to any rights you may have under applicable law.",
      },
      {
        heading: "24. Regulatory position",
        body: "Crowth is designed as an educational and simulation platform. Crowth does not currently provide users with a facility to execute securities trades, hold investment funds, or manage investments through the Platform. Nothing in these Terms should be interpreted as an offer to provide regulated financial services where authorisation is required by law.",
      },
      {
        heading: "25. Entire agreement",
        body: "These Terms, together with the Crowth Privacy Policy, Cookies Policy, and other policies expressly incorporated into these Terms, form the agreement governing your use of Crowth. If any provision is found to be invalid or unenforceable, the remaining provisions continue to apply to the extent permitted by law.",
      },
      {
        heading: "26. Contact us",
        body: "For questions, legal enquiries, privacy requests, or support relating to Crowth, contact INVESTIO GROUP OF COMPANIES (PTY) LTD at hello@crowthza.com, or use the official contact channels provided through the Crowth Platform (https://crowthza.app).",
      },
    ],
  },
  privacy: {
    id: "privacy",
    title: "Privacy Policy",
    updated: "7 September 2026",
    subtitle:
      "INVESTIO GROUP OF COMPANIES (PTY) LTD · Registration No. 2026/546441/07 · Republic of South Africa",
    sections: [
      {
        heading: "1. Introduction",
        body: "This Privacy Policy explains how Crowth collects, uses, stores, protects and shares personal information when you use the Crowth website, mobile application and related services. Crowth is an educational fintech platform operated by INVESTIO GROUP OF COMPANIES (PTY) LTD (Registration No. 2026/546441/07). Crowth helps users explore market information, compare companies, build and track demo portfolios, and use educational AI features. This Privacy Policy describes how we process personal information when you create an account, use Crowth, communicate with us, or otherwise interact with our services.",
      },
      {
        heading: "2. Who we are",
        body: "The responsible operator for Crowth is INVESTIO GROUP OF COMPANIES (PTY) LTD, Registration No. 2026/546441/07, Republic of South Africa. Crowth is designed for education and simulation. It does not hold customer funds, execute trades, or operate a brokerage account for users. Website: https://crowthza.app.",
      },
      {
        heading: "3. Information we collect",
        body: "Account and identity information: email address and account authentication information; name and basic profile information where provided by you or received through a configured sign-in provider; authentication-provider information when you choose a third-party sign-in method such as Google, where available. Portfolio and learning information: demo portfolio names, holdings, amounts, performance information and settings; risk preferences, educational goals and other learning preferences you choose to provide; watchlists, comparisons and related activity where these features are available. Communications: messages and prompts you submit to Crowth’s AI features; support requests, feedback and other communications you send to us. Technical and usage information: device type, browser, operating system and session information; IP address and technical logs generated when services are accessed; app and feature usage information, performance information, crash reports and error information.",
      },
      {
        heading: "4. How we collect information",
        body: "We may collect information when you create or use a Crowth account; sign in through email/password or a configured third-party authentication provider; create or update demo portfolios and preferences; use the AI Advisor or submit support requests; or use the website or mobile application, which may generate technical, security and performance logs.",
      },
      {
        heading: "5. How we use personal information",
        body: "We use personal information for purposes including creating and managing your account; keeping you signed in and providing authentication and security controls; saving and synchronising your demo portfolio and preferences; providing educational features, including AI-assisted explanations and portfolio tools; providing customer support and responding to requests; detecting abuse, fraud, suspicious activity and security incidents; monitoring reliability, crashes and technical performance; understanding feature usage and improving Crowth; and complying with applicable legal, regulatory and contractual obligations.",
      },
      {
        heading: "6. Lawful processing",
        body: "We process personal information only where there is a lawful justification under applicable law. Depending on the circumstances, this may include your consent, the need to provide or administer services you request, compliance with legal obligations, and other lawful grounds or interests recognised by applicable data-protection law. Where processing is based on consent, you may withdraw that consent where the law permits. Withdrawal does not necessarily affect processing that was lawfully carried out before withdrawal or processing that has another lawful justification.",
      },
      {
        heading: "7. Investment education and demo portfolio data",
        body: "Crowth may store information relating to demo portfolios, including simulated holdings, demo amounts, portfolio settings, performance results and related preferences. This information is used to provide the educational simulation and related features. Demo portfolio information is not a record of money held by Crowth on your behalf and does not represent a real brokerage account or real investment transaction.",
      },
      {
        heading: "8. AI Advisor and AI processing",
        body: "When you use Crowth’s AI features, the prompts, questions and other information you submit may be processed by the AI infrastructure used to provide the feature. We use AI to provide educational responses, explanations and general market-learning assistance. Do not submit passwords, payment-card information, government identification numbers, or other highly sensitive information into AI prompts unless specifically required and lawfully supported. AI responses can be incomplete, inaccurate or outdated and are not financial, investment, tax or legal advice. We do not represent that an AI response is suitable for your personal circumstances.",
      },
      {
        heading: "9. Market data",
        body: "Crowth may display market information obtained from external market-data providers. Market prices and other public market information are generally not personal information about you. However, technical logs associated with requests to obtain or display that information may contain information such as IP address, timestamps or other operational data.",
      },
      {
        heading: "10. Cookies and similar technologies",
        body: "Crowth may use cookies and similar technologies for essential functions, authentication, security, preferences, analytics and performance monitoring. Essential technologies help keep sessions working and support authentication. Security technologies help detect abuse, suspicious activity and account-protection events. Analytics technologies help us understand feature usage, engagement, performance and errors. You can normally manage, delete or restrict cookies through your browser settings. Some functionality may not work correctly if essential cookies or similar technologies are disabled. See the Crowth Cookies Policy for further information.",
      },
      {
        heading: "11. Analytics and performance monitoring",
        body: "We may use analytics and monitoring services to understand how Crowth is used, diagnose errors, measure performance and improve reliability. Where reasonably possible, analytics may be aggregated or otherwise handled to reduce unnecessary identification.",
      },
      {
        heading: "12. Third-party service providers",
        body: "Crowth relies on selected third-party technology providers to operate parts of the service. Depending on the feature and configuration, these may include: Supabase (account authentication, database and related cloud services); Cloudflare (hosting, application infrastructure, security and Workers AI services where configured); Finnhub (market-data services); PostHog (product analytics and usage insights); Sentry (application error and performance monitoring). Other hosting, infrastructure, authentication, security or AI providers may be used where necessary to operate or improve Crowth. These providers may process information on our behalf and are expected to handle it according to applicable contracts, security requirements and data-protection obligations.",
      },
      {
        heading: "13. International data transfers",
        body: "Some service providers used by Crowth may process information in countries outside South Africa. Where personal information is transferred or made accessible across borders, we will take reasonable steps to apply safeguards required by applicable law, including POPIA where applicable.",
      },
      {
        heading: "14. Data security",
        body: "We use reasonable technical and organisational measures intended to protect personal information against unauthorised access, loss, misuse, alteration or disclosure. Measures may include encryption in transit, access controls, authentication controls, security monitoring and infrastructure protections. No internet-connected service can be guaranteed to be completely secure. You are responsible for keeping your account credentials confidential and for notifying us of suspected unauthorised access.",
      },
      {
        heading: "15. Data retention",
        body: "We retain personal information only for as long as reasonably necessary for the purposes for which it was collected, including providing services, maintaining security, resolving disputes, enforcing agreements, and meeting legal or regulatory obligations. When information is no longer required, we may delete it, anonymise it, or securely dispose of it. Deletion from active systems may not result in immediate removal from backups, security logs or records that must be retained for legitimate or legal reasons.",
      },
      {
        heading: "16. Sharing and disclosure",
        body: "We do not sell your personal information. We may disclose information where reasonably necessary to service providers that help us operate Crowth; protect the security, rights and safety of Crowth, users or others; detect or investigate fraud, abuse or security incidents; comply with applicable law, court orders, regulatory requirements or lawful requests; or support a merger, acquisition, restructuring or transfer of business assets where applicable. We seek to limit disclosures to information that is reasonably necessary for the relevant purpose.",
      },
      {
        heading: "17. Your POPIA rights",
        body: "Subject to applicable law and any lawful limitations, you may have rights relating to your personal information, including the right to request access to personal information we hold about you; request correction of inaccurate or incomplete information; request deletion of personal information where there is a lawful basis to do so; object to certain processing; request restriction of processing where applicable; withdraw consent where processing relies on consent; and lodge a complaint with the Information Regulator where you believe your rights have been infringed. Requests may be made through the official Crowth support channels. We may need to verify your identity before completing a request.",
      },
      {
        heading: "18. Direct marketing",
        body: "Where Crowth sends direct marketing communications, it will do so only as permitted by applicable law. You may opt out of marketing communications using the available unsubscribe or preference mechanism.",
      },
      {
        heading: "19. Children’s privacy",
        body: "Crowth is intended for users who are at least 18 years old. We do not knowingly collect personal information from children in circumstances where doing so would be unlawful. If you believe a child has provided personal information to us unlawfully, please contact us so that the matter can be reviewed.",
      },
      {
        heading: "20. Account deletion",
        body: "You may request deletion of your Crowth account through the in-app profile deletion process or official Crowth support channels. We may retain certain information where required by law or reasonably necessary for security, fraud prevention, dispute resolution, record keeping or enforcement of legal rights. Local demo data stored in your browser may also be removed through your browser’s site-data or storage settings.",
      },
      {
        heading: "21. Data breaches and security incidents",
        body: "If we become aware of a security compromise involving personal information, we will assess the incident and take reasonable steps to contain, investigate and remediate it. Where notification is required by applicable law, including POPIA, we will notify the relevant regulator and/or affected data subjects in accordance with the applicable requirements.",
      },
      {
        heading: "22. Complaints and the Information Regulator",
        body: "You may first contact Crowth through its official support channels so that we can investigate your concern. You may also have the right to lodge a complaint with the Information Regulator of South Africa under applicable data-protection law.",
      },
      {
        heading: "23. Changes to this Privacy Policy",
        body: "We may update this Privacy Policy when our services, technology, legal obligations or data practices change. The updated version will show a revised “Last updated” date. Where required, we will provide additional notice or obtain consent.",
      },
      {
        heading: "24. Contact details",
        body: "Privacy and data-protection enquiries may be directed to INVESTIO GROUP OF COMPANIES (PTY) LTD at hello@crowthza.com, or through the official Crowth support channels at https://crowthza.app.",
      },
      {
        heading: "25. Related policies",
        body: "Related policies available on the Platform include the Terms of Service (https://crowthza.app/legal/terms), this Privacy Policy (https://crowthza.app/legal/privacy), and the Cookies Policy (https://crowthza.app/legal/cookies).",
      },
    ],
  },
  cookies: {
    id: "cookies",
    title: "Cookies Policy",
    updated: "7 September 2026",
    subtitle:
      "INVESTIO GROUP OF COMPANIES (PTY) LTD · Registration No. 2026/546441/07 · Republic of South Africa",
    sections: [
      {
        heading: "1. Introduction",
        body: "This Cookies Policy explains how Crowth uses browser storage, cookies and similar technologies to provide authentication, security, preferences and core application functionality. Crowth is an educational fintech platform operated by INVESTIO GROUP OF COMPANIES (PTY) LTD (Registration No. 2026/546441/07). Some of these technologies are essential to the operation and security of Crowth. Because Crowth also uses browser storage for locally saved demo portfolio information, clearing site data may affect your local application state.",
      },
      {
        heading: "2. What are cookies and browser storage?",
        body: "Cookies are small pieces of information that a website may store in your browser. Similar technologies include local storage and session storage, which allow an application to save information in the browser without using traditional cookies. Crowth uses these technologies together where necessary to provide authentication, maintain sessions, remember preferences and support core application functionality.",
      },
      {
        heading: "3. What Crowth uses",
        body: "Essential browser storage: Crowth uses browser storage, including local storage and session storage, for essential functions such as keeping your application session working; supporting secure authentication and sign-in flows; supporting PKCE-based authentication flows where configured; remembering locally saved demo portfolio information; and remembering relevant application preferences. These technologies are considered essential because disabling or clearing them can prevent parts of Crowth from working correctly. Authentication and security: Browser storage and related technologies may be used to maintain secure authentication state and protect sign-in flows. Crowth may use PKCE as part of its authentication architecture. Security-related storage or cookies may also be used by authentication or infrastructure providers where required to protect accounts, prevent abuse, or maintain reliable service operation.",
      },
      {
        heading: "4. Third-party cookies and technologies",
        body: "Google Sign-In: If you choose Google sign-in, Google may use cookies or similar technologies as part of its authentication process. These technologies are controlled by Google and may be subject to Google’s own privacy and cookie practices. Crowth does not control third-party cookies that are required by an external authentication provider. Hosting and infrastructure providers: Infrastructure or hosting providers may use technical cookies or similar technologies for functions such as performance, reliability, security and abuse prevention. The specific technologies used may vary based on the production configuration of Crowth.",
      },
      {
        heading: "5. What we do not use cookies for",
        body: "Crowth’s core use of browser storage is to operate the application, support authentication, remember local demo information and maintain security. We do not sell personal information through cookies. Where analytics or other non-essential technologies are used, their purpose is described in the applicable Crowth Privacy Policy and related notices.",
      },
      {
        heading: "6. Managing cookies and site data",
        body: "You can normally manage cookies and browser storage through your browser settings. Depending on your browser, you can block, delete, restrict or clear cookies and site data. You can clear Crowth site data through your browser’s privacy or site-data settings. Clearing this data may sign you out of Crowth; remove locally stored demo portfolio data; remove locally saved preferences; require you to complete the sign-in process again; and affect functionality that depends on browser storage. Clearing browser storage does not necessarily delete account or cloud data stored by Crowth or its service providers. Account deletion should be requested through the official Crowth account-deletion process.",
      },
      {
        heading: "7. Essential technologies and consent",
        body: "Technologies that are strictly necessary for authentication, security and core application functionality may be used because they are required to provide the service you request. Where applicable law requires consent for a particular cookie or similar technology, Crowth will seek and manage that consent as required.",
      },
      {
        heading: "8. Privacy and personal information",
        body: "Cookies and browser storage may contain or be associated with information relating to your device, session, account or use of Crowth. Where such information qualifies as personal information under applicable law, Crowth will process it in accordance with its Privacy Policy and applicable data-protection requirements. For more information about the collection, use, retention, security and disclosure of personal information, please review the Crowth Privacy Policy at https://crowthza.app/legal/privacy.",
      },
      {
        heading: "9. Changes to this Cookies Policy",
        body: "We may update this Cookies Policy when Crowth’s technology, services, third-party providers or legal requirements change. The revised version will display a new “Last updated” date. Where required, we may also provide additional notice or request consent.",
      },
      {
        heading: "10. Contact details",
        body: "Questions about cookies, browser storage or privacy may be directed to INVESTIO GROUP OF COMPANIES (PTY) LTD at hello@crowthza.com, or through the official Crowth support channels at https://crowthza.app.",
      },
      {
        heading: "11. Related policies",
        body: "Related policies available on the Platform include the Terms of Service (https://crowthza.app/legal/terms), the Privacy Policy (https://crowthza.app/legal/privacy), and this Cookies Policy (https://crowthza.app/legal/cookies).",
      },
    ],
  },
};

export function isLegalPolicyId(value: string): value is LegalPolicyId {
  return value === "terms" || value === "privacy" || value === "cookies";
}
